Feature/sign in
davicruzof/meusbeats pull request #3
Opened 2021-11-25 15:01 UTC by davicruzof

Tela de login com dois campo, sendo os mesmos para preenchimento do dados de acesso do usuário ( usuário e senha ) e uma botão para criação de uma nova conta, os inputs do campos são do tipo outlined.
Para implementação da mesma fiz o uso da lib styled-components para manipulação do style, ainda nessa feature foi adicionado as fontes da interface, tambem foi inserido a lib react-native-icons para utilização dos icones do app, ainda nessa feature foi configurado o lint e prettier.

2021-11-30 13:01 UTC, FelipeNunes04 requested changes

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/Button/styles.js
> +import { Fonts } from '../../utils/Fonts';
Opa, configura path alias para seu projeto: https://christianlydemann.com/simpler-typescript-paths-with-path-aliases/
Esses imports com `../` não são uma boa prática

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInput/index.js
> +  ...rest }) => {
Você precisa tirar suas props, cria uma interface Props nesse arquivo mesmo.

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInput/index.js
> +    }
Isso tá muito complexo, analisa como simplificar essa lógica.
```suggestion
    if(isFocused ) {
      setBorder(true)
    } else {
      setBorder(false)
    }
    
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInput/index.js
> +        placeholder={isFocused ? "" : placeholder}
Esse tipo de lógica deve ficar em uma variável.
```suggestion
        const placeholder = isFocused ? "" : placeholder;
        ...
        placeholder={placeholder}
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInputIcon/index.js
> +  active, label, updateIcon, ...props }) => {
Aqui precisa cria uma interface para suas props também.

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInput/index.js
> +  ...rest }) => {
Todos as suas funções e métodos devem ter o tipo de retorno.
```suggestion
export const TextInput = ({
  isPassword = true,
  color,
  placeholder,
  label,
  active,
  errorInput = false, 
  msgError = "",
  ...rest }): ReactElement => {
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInput/styles.js
> +import { Fonts } from '../../utils/Fonts';
Substituir por Path Alias também.
```suggestion
import { Colors } from '@utils/Colors';
import { Fonts } from '@utils/Fonts';
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInputIcon/index.js
> +        }}
Usar styled components

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInputIcon/index.js
> +  active, label, updateIcon, ...props }) => {
Adicionar o tipo de retorno do seu componente.
```suggestion
export const TextInputIcon = ({ 
  errorInput = false, 
  msgError = "",
  icon, 
  isPassword, 
  active, label, updateIcon, ...props }): ReactElement => {
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +import bgLogin from '../../assets/bg-login.png';
```suggestion
import bgLogin from '@assets/bg-login.png';
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInputIcon/index.js
> +import { Colors } from '../../utils/Colors';
```suggestion
import { Colors } from '@utils/Colors';
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInputIcon/index.js
> +import { TextInput } from '../TextInput';
```suggestion
import { TextInput } from '@components/TextInput';
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/TextInputIcon/index.js
> +            color="transparent"
Adicionar a cor transparente ao seu arquivo de cores e usar aqui

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +import { Colors } from '../../utils/Colors';
```suggestion
import { Button } from '@components/Button';
import { TextInputIcon } from '@components/TextInputIcon';
import { Colors } from '@utils/Colors';
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +export const SignIn = () => {
```suggestion
export const SignIn = (): ReactElement => {
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +        var requestOptions = {
Não é boa prática utilizar `var` no código
```suggestion
        const requestOptions = {
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +            result.message === 'Senha inválida' ? setErrorPassword(true) : setErrorPassword(false);
Não é recomendado usar strings hard coded no código, o ideal é coloca-las em constantes ou em arquivos de tradução.

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +    const login = async() => {
```suggestion
    const login = async (): ReactElement => {
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +            result.message === 'Senha inválida' ? setErrorPassword(true) : setErrorPassword(false);
Não se pode misturar a camada de View com a camada que faz comunicação com apis estercas, você tem que separar isso na sua arquitetura.

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +                            icon={userView ? 'eye-off' : 'eye'}
Esse tipo de lógica deve estar em uma variável.
```suggestion
                            const textInputIcon = userView ? 'eye-off' : 'eye';
                            ...
                            icon={textInputIcon}
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +                            icon={passwordView ? 'eye-off' : 'eye'}
Esse tipo de lógica deve estar em uma variável.

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +                            active={password.length > 0}
Esse tipo de lógica deve estar em uma variável.

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +                            style={{ marginTop: 49}}
Todos os styles devem ficar no arquivos de styles

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +                                    }
Extrair essa lógica para uma função.

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/style.js
> +import { Colors } from "../../utils/Colors";
```suggestion
import { Fonts } from "@utils/Fonts";
import { Colors } from "@utils/Colors";
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/views/SignIn/index.js
> +        myHeaders.append("Content-Type", "application/json");
Aqui tem muita lógica, você pode criar outros métodos para simplificar a leitura do código

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/Label/styles.js
> +import { Fonts } from '../../utils/Fonts';
```suggestion
import { Colors } from '@utils/Colors';
import { Fonts } from '@utils/Fonts';
```

2021-11-30 13:01 UTC, FelipeNunes04 commented on src/components/Button/index.js
> +export const Button = ({ text, ...props }) => {
Suas props devem ser tinadas e seu componente tem que indicar qual o retorno dele. Pode criar uma interface Props nesse arquivo mesmo.
```suggestion
export const Button = ({ text, ...props }: Props): ReactElement => {
```

2021-11-30 13:04 UTC, davicruzof commented
![](https://github.trello.services/images/mini-trello-icon.png) [View Sign In](https://trello.com/c/ak9aZwnd/4-view-sign-in)

2021-12-03 19:15 UTC, FelipeNunes04 commented on App.tsx
> +import { SignIn } from './src/views/SignIn';
Opa @davicruzof, não é legal ter a pasta `src` nos seus imports, ajusta seu alias para importar a partir de `views`

2021-12-03 19:17 UTC, FelipeNunes04 commented on src/components/Button/index.tsx
> +    active: Boolean | false;
Aqui você não precisa definir esses valores padrões

2021-12-03 19:19 UTC, FelipeNunes04 commented on src/components/IconButton/styles.tsx
> +import Feather from 'react-native-vector-icons/Feather';
Não é uma boa prática importar arquivos do projeto antes de imports de bibliotecas externas

2021-12-03 19:20 UTC, FelipeNunes04 commented on src/components/Input/index.tsx
> +    errorInput: boolean | false;
Aqui também não precisa desses valores

2021-12-03 19:20 UTC, FelipeNunes04 commented on src/components/Input/index.tsx
> +        setShowLabel(!isFocused && !status ? false : true);
Lógicas assim não podem ficar dentro do render, o recomendado é colocar em uma variável ou método

2021-12-03 19:21 UTC, FelipeNunes04 commented on src/services/login.tsx
> +};
Adiciona uma linha em branco aqui

2021-12-03 19:22 UTC, FelipeNunes04 commented on src/views/SignIn/index.tsx
> +import { apiRequest } from '../../services/login';
Ajusta esse import também para usar um alias para Services

2021-12-03 19:24 UTC, FelipeNunes04 commented on src/views/SignIn/index.tsx
> +        setErrorPassword(res.message === msgErrorPassword ? true: false);
Não é legal colocar essa lógica na chamada do método, coloca em uma linha antes, deixa o código mais legível

2021-12-03 19:25 UTC, FelipeNunes04 commented on src/views/SignIn/styles.tsx
> +`;
Faltou uma linha em branco no final do arquivo

2021-12-03 19:35 UTC, FelipeNunes04 commented on src/views/SignIn/index.tsx
> +import { Colors } from '@utils/Colors';
Você precisa organizar seus imports, coloca primeiro bibliotecas externas e depois importa seu código do projeto. Separa com uma linha em branco

2021-12-03 19:36 UTC, FelipeNunes04 commented on src/components/Label/styles.ts
> +import { Colors } from '@utils/Colors';
Para organizar melhor, você pode colocar uma linha em branco entre esses imports

2021-12-03 19:36 UTC, FelipeNunes04 commented on src/components/Input/styles.tsx
> +import styled from 'styled-components/native';
Esse import deve ser o primeiro do arquivo.

2021-12-09 12:05 UTC, FelipeNunes04 commented on src/views/SignIn/index.tsx
> +import bg from '@assets/bgLogin.png';
Dá uma olhada nesse link para conseguir importar imagens: https://stackoverflow.com/questions/43823289/how-to-import-image-svg-png-in-a-react-component

2021-12-09 12:06 UTC, FelipeNunes04 commented on src/views/SignIn/index.tsx
> +};
Aqui você tem sua lógica de login misturada com as telas, o ideal seria ter uma camada de lógica e uma camada onde você desenha seu layout.

2021-12-13 18:45 UTC, FelipeNunes04 commented on src/components/Input/styles.tsx
> +import styled from 'styled-components/native';
opa @davicruzof, faltou ajustar o import aqui

2021-12-13 18:46 UTC, FelipeNunes04 approved these changes

2021-12-14 18:04 UTC, merged